# Generated by Django 3.0.1 on 2020-02-28 08:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200228_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 28, 8, 25, 38, 138948, tzinfo=utc), verbose_name='Date Posted'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 28, 8, 25, 38, 138948, tzinfo=utc), verbose_name='Created Date'),
        ),
    ]
