# Generated by Django 3.0.1 on 2020-03-01 09:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200301_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 1, 9, 21, 11, 915941, tzinfo=utc), verbose_name='Date Posted'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 1, 9, 21, 11, 900346, tzinfo=utc), verbose_name='Created Date'),
        ),
    ]
